version: '3'

services:
  react-app:
      container_name: 'react-app'
      image: poc/react
      build: ./react-app
      environment: 
        NODE_ENV: production
      ports:
        - 3000:80
      links:
        - graphql-api  
  graphql-api:
    container_name: 'graphql'
    image: poc/graphql
    build: ./graphQL-api/
    environment:
      NODE_ENV: production
    ports:
      - 4000:4000
    links:
      - rest-api-1
      - rest-api-2
      - mongo
    depends_on:
      - rest-api-1
      - rest-api-2

  rest-api-1: 
      container_name: 'rest-api-1'
      image: poc/rest-api-1
      build: ./rest-api/
      ports:  
          - 8001
  rest-api-2: 
      container_name: 'rest-api-2'
      image: poc/rest-api-2
      build: ./rest-api2/
      ports:  
          - 8002    
  mongo: 
    container_name: 'mongo-database'
    image: mongo
    ports: 
      - 27017:27017
    volumes:
      -  local-mongo-data:/data/db
volumes:
  local-mongo-data:
