version: '3'

services:
  graphql-api:
    container_name: 'graphQL'
    image: graphql
    build: ./graphQL-api/
    environment:
      NODE_ENV: production
    ports:
      - 4000:3333
    # links: 
    #   - mongo
    # depends_on: 
    #   - mongo
  mongo: 
    container_name: 'rest-api1'
    image: rest1
    ports: 
      - 80:3334
#     volumes:
#       -  mongo-data:/data/db
# volumes:
#   mongo-data: