FROM node
ENV NODE_ENV production
WORKDIR /app
COPY ["package.json", "package-lock.json*", "npm-shrinkwrap.json*", "./"]
RUN npm install --production --silent && mv node_modules ../
RUN npm i -g webpack
RUN webpack
COPY . .

FROM node
RUN npm i -g serve
ENV NODE_ENV production
WORKDIR /app
COPY --from=0 /app/public .
CMD serve -l 80 -s .