FROM node:8.9-alpine
ENV NODE_ENV production
WORKDIR /usr/public
COPY ["package.json", "package-lock.json*", "npm-shrinkwrap.json*", "./"]
RUN npm install --production --silent && mv node_modules ../
COPY . .
EXPOSE 3333
CMD node src/server/app.js